const SET_INITIAL_USER_INFO = 'SET_INITIAL_USER_INFO';
const SET_PUBLIC_KEY = 'SET_PUBLIC_KEY';
const SET_MANAGER_EMAIL = 'SET_MANAGER_EMAIL';
const SET_MANAGER_EMAIL_REQUIRED = 'SET_MANAGER_EMAIL_REQUIRED';
const SET_USER_AUTHENTICATED = 'SET_USER_AUTHENTICATED';
const SET_USER_AUTHENTICATION_START = 'SET_USER_AUTHENTICATION_START';
const SET_USER_AUTHENTICATION_FAIL_REASON = 'SET_USER_AUTHENTICATION_FAIL_REASON';

const GET_PEOPLE_INFO = 'GET_PEOPLE_INFO';
const GET_PEOPLE_INFO_SUCCESS = 'GET_PEOPLE_INFO_SUCCESS';
const GET_PEOPLE_INFO_FAILURE = 'GET_PEOPLE_INFO_FAILURE';

const GET_LEARNER_TASKS = "GET_LEARNER_TASKS";
const GET_LEARNER_TASKS_SUCCESS = "GET_LEARNER_TASKS_SUCCESS";
const GET_LEARNER_TASKS_FAILURE = "GET_LEARNER_TASKS_FAILURE";

const GET_PORTAL_LOGIN = "GET_PORTAL_LOGIN";
const GET_PORTAL_LOGIN_SUCCESS = "GET_PORTAL_LOGIN_SUCCESS";
const GET_PORTAL_LOGIN_FAILURE = "GET_PORTAL_LOGIN_FAILURE";

const GET_LEARNER_JWTOKEN = "GET_LEARNER_JWTOKEN";
const GET_LEARNER_JWTOKEN_SUCCESS = "GET_LEARNER_JWTOKEN_SUCCESS";
const GET_LEARNER_JWTOKEN_FAILURE = "GET_LEARNER_JWTOKEN_FAILURE";

const GET_NEWSFEED_API = "GET_NEWSFEED_API";
const GET_NEWSFEED_API_SUCCESS = "GET_NEWSFEED_API_SUCCESS";
const GET_NEWSFEED_API_FAILURE = "GET_NEWSFEED_API_FAILURE";

const GET_TMS_COURSES = "GET_TMS_COURSES";
const GET_TMS_COURSES_SUCCESS = "GET_TMS_COURSES_SUCCESS";
const GET_TMS_COURSES_FAILURE = "GET_TMS_COURSES_FAILURE";

const GET_TMS_LOGIN = "GET_TMS_LOGIN";
const GET_TMS_LOGIN_SUCCESS = "GET_TMS_LOGIN_SUCCESS";
const GET_TMS_LOGIN_FAILURE = "GET_TMS_LOGIN_FAILURE";

const GET_TMS_LOGOUT = "GET_TMS_LOGOUT";
const GET_TMS_LOGOUT_SUCCESS = "GET_TMS_LOGOUT_SUCCESS";
const GET_TMS_LOGOUT_FAILURE = "GET_TMS_LOGOUT_FAILURE";

const STOP_TMS_API_PROPAGATION = "STOP_TMS_API_PROPAGATION";

const GET_ANNOUNCEMENTS = "GET_ANNOUNCEMENTS";
const GET_ANNOUNCEMENTS_SUCCESS = "GET_ANNOUNCEMENTS_SUCCESS";
const GET_ANNOUNCEMENTS_FAILURE = "GET_ANNOUNCEMENTS_FAILURE";

const GET_JWK_PUBLIC_KEY = "GET_JWK_PUBLIC_KEY";
const GET_JWK_PUBLIC_KEY_SUCCESS = "GET_JWK_PUBLIC_KEY_SUCCESS";
const GET_JWK_PUBLIC_KEY_FAILURE = "GET_JWK_PUBLIC_KEY_FAILURE";

const DESTROY_SESSION = "DESTROY_SESSION";
const TRIGGER_TOAST = "TRIGGER_TOAST";
const RESET_TOAST = "RESET_TOAST";

const GET_RENEWAL_INFO = 'GET_RENEWAL_INFO';
const GET_RENEWAL_INFO_SUCCESS = 'GET_RENEWAL_INFO_SUCCESS';
const GET_RENEWAL_INFO_FAILURE = 'GET_RENEWAL_INFO_FAILURE';

const GET_ACTIVE_COURSE_INFO = 'GET_ACTIVE_COURSE_INFO';
const GET_ACTIVE_COURSE_SUCCESS = 'GET_ACTIVE_COURSE_SUCCESS';
const GET_ACTIVE_COURSE_FAILURE = 'GET_ACTIVE_COURSE_FAILURE';


export {
    SET_INITIAL_USER_INFO,
    SET_PUBLIC_KEY,
    SET_MANAGER_EMAIL,
    SET_MANAGER_EMAIL_REQUIRED,
    SET_USER_AUTHENTICATED,
    SET_USER_AUTHENTICATION_START,
    SET_USER_AUTHENTICATION_FAIL_REASON,
    GET_PEOPLE_INFO,
    GET_PEOPLE_INFO_SUCCESS,
    GET_PEOPLE_INFO_FAILURE,
    GET_LEARNER_TASKS,
    GET_LEARNER_TASKS_SUCCESS,
    GET_LEARNER_TASKS_FAILURE,
    GET_PORTAL_LOGIN, 
    GET_PORTAL_LOGIN_SUCCESS,
    GET_PORTAL_LOGIN_FAILURE,
    GET_LEARNER_JWTOKEN,
    GET_LEARNER_JWTOKEN_SUCCESS,
    GET_LEARNER_JWTOKEN_FAILURE,
    GET_NEWSFEED_API,
    GET_NEWSFEED_API_SUCCESS,
    GET_NEWSFEED_API_FAILURE,
    GET_TMS_COURSES,
    GET_TMS_COURSES_SUCCESS,
    GET_TMS_COURSES_FAILURE,
    GET_TMS_LOGIN,
    GET_TMS_LOGIN_SUCCESS, 
    GET_TMS_LOGIN_FAILURE,
    GET_TMS_LOGOUT, 
    GET_TMS_LOGOUT_SUCCESS, 
    GET_TMS_LOGOUT_FAILURE,
    STOP_TMS_API_PROPAGATION,
    GET_ANNOUNCEMENTS,
    GET_ANNOUNCEMENTS_SUCCESS,
    GET_ANNOUNCEMENTS_FAILURE,
    GET_JWK_PUBLIC_KEY,
    GET_JWK_PUBLIC_KEY_SUCCESS,
    GET_JWK_PUBLIC_KEY_FAILURE,
    DESTROY_SESSION,
    TRIGGER_TOAST,
    RESET_TOAST,
    GET_RENEWAL_INFO,
    GET_RENEWAL_INFO_SUCCESS,
    GET_RENEWAL_INFO_FAILURE,
    GET_ACTIVE_COURSE_INFO,
    GET_ACTIVE_COURSE_SUCCESS,
    GET_ACTIVE_COURSE_FAILURE

}